# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/favicon.png"
    high_res_favicon: "/favicon.png"
    apple_touch_icon: "/favicon.png"
    keywords: 

# Jump Links Settings
url:
    about: "/about"
    rss: "/atom.xml"
    daily_pic: "#"
    logo: "/images/default_avatar.jpg"


# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Schemes
#scheme: Paradox
scheme: Isolation

# UI & UX: slogan, color, effect
uiux:
    fab: true
    fab_icon: add
    slogan: "每天变得更好一点"
    theme_color: "#039BE5"
    theme_sub_color: "#00BCD4"
    hyperlink_color: "#039BE5"
    android_chrome_color: "#039BE5"
    nprogress_color: "#FF4081"
    nprogress_buffer: "800"
    
# JS Effect Switches
js_effect:
    fade: true
    smoothscroll: true
    fab_hover_in: false
    fab_hover_out: true

# Reading experience
# markdown available value:
#     Material | Github | Plain
reading:
    markdown: Github
    entry_excerpt: 80

# Thumbnail Settings
thumbnail:
    purecolor: 
    random_amount: 5

# Background Settings
background:
    purecolor: "#F5F5F5"
    #bgimg: "/img/bg.png"

# Images Settings
img:
    logo: "/img/logo.png"
    avatar: "/images/default_avatar.jpg"
    daily_pic: "/img/daily_pic.png"
    sidebar_header: "/img/sidebar_header.png"
    footerico: "/img/footer/footer_ico-"
    #upyun_logo: "/img/upyun_logo.png"
    random_thumbnail: "/img/random/"

# Custom Fonts
fonts: Roboto, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", Arial, sans-serif

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# SNS Menu
sns:
    email: "beijiu572@gmail.com"
    twitter: "https://twitter.com/cielpy5"
    facebook: 
    googleplus: "https://plus.google.com/+KevinGuo572/"
    weibo: 
    instagram: "https://www.instagram.com/cielpy5/"
    tumblr: 
    github: "https://github.com/cielpy"

# Sidebar User Dropdown
dropdown: 
    Email Me: 
        link: "mailto:beijiu572@gmail.com"
        icon: email

# Pages Menu
pages:
  标签云: "/tags"
  Wiki: "https://wiki.imciel.com/"


# ---------------------------------------------------------------
# Integrated Services
# ---------------------------------------------------------------
    
# Comment Systems
# Available value:
#     duoshuo | disqus
comment:
    use: disqus
    shortname: cielpark
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key: 
        
# Leancloud Views
leancloud:
    enable: false
    app_id: #你的app_id
    app_key: #你的app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"
    
# Busuanzi 不蒜子 Views
busuanzi:
    enable: false
    all_site_uv: false
    post_pv: false
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"
